function show_para(parameters,idx)
    str = "Field " + round(parameters.field_gradient(idx)) + ...
      " VM1 " + round(parameters.VMI1(idx)) + ...
      " VM2 " + round(parameters.VMI2(idx)) + ...
      " e_grid " + round(parameters.e_grid(idx)) + ...
      " dt_e " + round(parameters.dt_e(idx));
disp(str);
    
end
